version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "9292:9292"
    links:
      - postgres
    privileged: true
    environment:
      DATABASE_URL: postgresql://admin:secretpassword@postgres/orders
      POSTGRES_USER: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: orders
      POSTGRES_PASSWORD: secretpassword
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: orders
